/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.13
 * Generated at: 2019-02-21 07:42:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<meta http-equiv=\"refresh\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.sessionTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; url=logout\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/images/wdog.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/jquery.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/select.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/font-awesome/css/font-awesome.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/popper.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.dataTables.min.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/common.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".focus {\r\n");
      out.write("\tborder: 2px solid #AA88FF;\r\n");
      out.write("\tbackground-color: #FFEEAA;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("<!-- navbar-fixed-top -->\r\n");
      out.write("<div>\r\n");
      out.write(" <!-- class= navbar-header -->\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t <strong><span style=\"color:red;\">\\\\/\\/</span>\r\n");
      out.write("\t\t\t\t <span style=\"color:blue;\">a</span>\r\n");
      out.write("\t\t\t\t <span style=\"color:lightgreen\">t</span>\r\n");
      out.write("\t\t\t\t <span style=\"color:yellow\">c</span>\r\n");
      out.write("\t\t\t\t <span style=\"color:cyan\">h</span>\r\n");
      out.write("\t\t\t\t <span style=\"color: #FFFFCC\"> [|)og</span></strong>\r\n");
      out.write("\t\t\t\t <span style=\"flaot: left; padding-left: 0px; padding-top: -10px;\">\r\n");
      out.write("\t\t\t\t\t<img height=\"45px\" \tsrc=\"/images/wdog.jpg\">\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div id=\"navbar\" class=\"collapse navbar-collapse mfont\"  role =\"navigation\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li id=\"tab1\"  class=\"active\"><a href=\"status\"  title=\"Check Running and Others Status\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-home\" aria-hidden=\"true\"></i> Status</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"tab2\"><a href=\"configfile\" title=\"Setting configuation for application run\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-cog\" aria-hidden=\"true\"></i> Settings </a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\" id=\"tab3\">\r\n");
      out.write("\t\t\t        <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"javascript:void(0)\" title=\"Show Input Folder\">\r\n");
      out.write("\t\t\t        <i class=\"fa fa-expand\" aria-hidden=\"true\"></i> Input\r\n");
      out.write("\t\t\t        <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t        <ul class=\"dropdown-menu mfont\">\r\n");
      out.write("\t\t\t          <li><a href=\"inputdir\"><i class=\"fa fa-folder-open-o\" aria-hidden=\"true\"></i>&nbsp; File </a></li>\r\n");
      out.write("\t\t\t          <li><a href=\"inputdirfin\"><i class=\"fa fa-folder-open-o\" aria-hidden=\"true\"></i>&nbsp; Fin </a></li>\r\n");
      out.write("\t\t\t          <li><a href=\"inputdirfbpay\"><i class=\"fa fa-folder-open-o\" aria-hidden=\"true\"></i>&nbsp; FBPay </a></li>\r\n");
      out.write("\t\t\t    \t  <li><a href=\"inputdirso\"><i class=\"fa fa-folder-open-o\" aria-hidden=\"true\"></i>&nbsp; SO  </a></li>\r\n");
      out.write("\t\t\t          <li><a href=\"inputdirnonedi\"><i class=\"fa fa-folder-open-o\" aria-hidden=\"true\"></i>&nbsp; NEdi</a></li>\r\n");
      out.write("\t\t\t          <li><a href=\"inputdirbulk\"><i class=\"fa fa-folder-open-o\" aria-hidden=\"true\"></i>&nbsp; BLK</a></li>\r\n");
      out.write("\t\t\t          \r\n");
      out.write("\t\t\t        </ul>\r\n");
      out.write("\t\t\t     </li>\r\n");
      out.write("\t\t\t\t<li id=\"tab4\"><a href=\"responseout\" title=\"Show all files in Output Folder\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-folder-open\" aria-hidden=\"true\"></i>  Output</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"tab5\"><a href=\"archiveout\" title=\"Show all files in Archive Folder\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-folder-open\" aria-hidden=\"true\"></i> Archive</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"tab8\"><a href=\"failuredir\" title=\"Show all Failure files in Failure Folder\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-folder-open\" aria-hidden=\"true\"></i> Failure</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"tab6\"><a href=\"fileupload\" title=\"Can upload valid file to Input Folder\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-upload\" aria-hidden=\"true\"></i> Upload File</a></li>\r\n");
      out.write("\t\t\t    <li id=\"tab7\"><a href=\"reportspage\" title=\"Check Reports of Failure and Success Files\">\r\n");
      out.write("\t\t\t    <i class=\"fa fa-list\" aria-hidden=\"true\"></i>  Reports</a></li>\r\n");
      out.write("\t\t\t\t<li id=\"tab9\"><a href=\"logspage\" title=\"Check Error File Logs and Application Logs\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-history\" aria-hidden=\"true\"></i> Logs</a></li>\r\n");
      out.write("\t\t\t    <li id=\"tab11\"><a href=\"planid\" title=\"Can see all plan id in coming run cycle of so batch job\">\r\n");
      out.write("\t\t\t    <i class=\"fa fa-briefcase\" aria-hidden=\"true\"></i>&nbsp; PlanID</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- UI -->\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\" style=\"padding-right: 30px;\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" title=\"Username\"><i class=\"fa fa-user-o\" aria-hidden=\"true\" style=\"color: yellow\"> </i>\r\n");
      out.write("\t\t\t\t\t  &nbsp;Hello: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\" id=\"tab10\">\r\n");
      out.write("\t\t\t\t        <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"javascript:void(0)\" title=\"Logout & User registration\">\r\n");
      out.write("\t\t\t\t        <span class=\"fa fa-address-book\"></span></a>\r\n");
      out.write("\t\t\t\t        <ul class=\"dropdown-menu mfont\" id=\"tab10\" >\r\n");
      out.write("\t\t\t\t          <li><a href=\"logout\"  title=\"Logout\"><i class=\"fa fa-sign-out\" aria-hidden=\"true\" style=\"color: red;font-size:15px;\"></i>&nbsp; Logout&nbsp;&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t          <li><a href=\"reguser\" title=\"Registration of user\"><i class=\"fa fa-user-plus\" aria-hidden=\"true\"></i>&nbsp;&nbsp; Add User</a></li>\r\n");
      out.write("\t\t\t\t          <li><a href=\"showusers\" title=\"All users\"><i class=\"fa fa-users\" aria-hidden=\"true\"></i>&nbsp;&nbsp; Show User</a></li>\r\n");
      out.write("\t\t\t\t          <li><a href=\"javascript:void(0)\" onclick=\"restoreUsers()\" title=\"Restore users\"><i class=\"fa fa-window-restore\" aria-hidden=\"true\"></i>&nbsp;&nbsp; Restore User</a></li>\r\n");
      out.write("\t\t\t\t        </ul>\r\n");
      out.write("\t\t\t      </li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<div style=\"padding-top: 80px;\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "model.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
